# Guest OS timezone
timezone: UTC
# Are we need check box updates for every 'vagrant up'?
box_check_update: false
# Virtual machine name
machine_name: pelias
# Virtual machine IP
ip: 192.168.66.66
# Virtual machine CPU cores number
cpus: 2
# Virtual machine RAM
memory: 8196

@todo Move there more configuration

domain: pelias.devel
https: false
